version: '3'

tasks:
  lint:
    cmds:
      - poetry run ruff check solve tests
      - poetry run mypy .
  style:
    cmds:
      - poetry run ruff format solve tests
  test:
    cmds:
      - poetry run pytest
  solve:
    cmds:
      - 'echo "2022.6.1: $(poetry run python3 solve/solve.py input 4)"'
      - 'echo "2022.6.2: $(poetry run python3 solve/solve.py input 14)"'
