version: '3'

tasks:
  lint:
    cmds:
      - yarn lint
  build:
    cmds:
      - yarn build
    sources:
      - src/**/*.ts
    generates:
      - dist/**/*.js
  style:
    cmds:
      - yarn format
  test:
    deps: [build]
    cmds:
      - yarn test
  solve:
    deps: [build]
    cmds:
      - 'echo -e "2022.5:\n$(yarn --silent start input)"'
