version: '3'

tasks:
  lint:
    cmds:
      - java -jar checkstyle-10.12.5-all.jar -c /google_checks.xml src/
  build:
    cmds:
      - yarn build
    sources:
      - src/**/*.ts
    generates:
      - dist/**/*.js
  test:
    deps: [build]
    cmds:
      - yarn test
  solve:
    deps: [build]
    cmds:
      - yarn --silent start
