version: '3'

tasks:
  lint:
    cmds:
      - cargo clippy
  test:
    cmds:
      - cargo test
  solve:
    cmds:
      - 'echo "2023.4.1: $(cargo run -q -- input)"'
      - 'echo "2023.4.2: $(cargo run -q -- --ranges input)"'
