version: '3'

tasks:
  lint:
    cmds:
      - cargo clippy
  test:
    cmds:
      - cargo test
  solve:
    cmds:
      - 'echo -e "2023.2:\n$(cargo run -q -- input --red 12 --green 13 --blue 14)"'
